### ISSUE TITLE
无法从mikanani获取RSS

### ISSUE THREAD

**Issue by pspbra** [std4453/mikanarr#11]
@Izumiko
使用了这位制作的docker，启动成功。已经成功登录网页端，添加pattern也没有问题

但是无法通过http://192.168.31.249:12306/RSS/Classic  获取到RSS订阅信息。
直接在浏览器访问该链接后只能看到如下信息，没有被转化后的详细信息被列出。
```

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<rss version="2.0">
<channel>
<title>Mikan Project - 列表模式</title>
<link>http://mikanani.me/RSS/Classic?</link>
<description>Mikan Project - 列表模式</description>
</channel>
</rss>
```

请问可能的原因是什么？能否有人告知

**Comment by Izumiko** [comment]
你要不试试原版的docker镜像？我打包时升级了依赖，不确定会不会引入一些不兼容的问题。

我自己使用时倒是能获得结果，用RSS/Classic的话只能拿到最近的一些记录（[列表第一页](https://mikanani.me/Home/Classic)），要是你添加的番剧里面最近没更新的话，可能信息就是空白的
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<rss version="2.0">
  <channel>
    <title>Mikan Project - 列表模式</title>
    <link>http://mikanani.me/RSS/Classic?</link>
    <description>Mikan Project - 列表模式</description>
    <item>
      <title>Love of Kill - S01E11 - Chinese - WEBDL 1080p</title>
      <pubDate>2022-03-24T00:33:44.243</pubDate>
      <enclosure type="application/x-bittorrent" length="480027616" url="https://mikanani.me/Download/20220324/9aac876cbc4ba1d3a5ce82cac18d61cfdc5c4498.torrent"/>
      <link>https://mikanani.me/Home/Episode/9aac876cbc4ba1d3a5ce82cac18d61cfdc5c4498</link>
      <guid isPermaLink="true">https://mikanani.me/Home/Episode/9aac876cbc4ba1d3a5ce82cac18d61cfdc5c4498</guid>
    </item>
  </channel>
</rss>
```

**Comment by pspbra** [comment]
> 你要不试试原版的docker镜像？我打包时升级了依赖，不确定会不会引入一些不兼容的问题。
> 
> 我自己使用时倒是能获得结果，用RSS/Classic的话只能拿到最近的一些记录（[列表第一页](https://mikanani.me/Home/Classic)），要是你添加的番剧里面最近没更新的话，可能信息就是空白的
> 
> ```
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <rss version="2.0">
>   <channel>
>     <title>Mikan Project - 列表模式</title>
>     <link>http://mikanani.me/RSS/Classic?</link>
>     <description>Mikan Project - 列表模式</description>
>     <item>
>       <title>Love of Kill - S01E11 - Chinese - WEBDL 1080p</title>
>       <pubDate>2022-03-24T00:33:44.243</pubDate>
>       <enclosure type="application/x-bittorrent" length="480027616" url="https://mikanani.me/Download/20220324/9aac876cbc4ba1d3a5ce82cac18d61cfdc5c4498.torrent"/>
>       <link>https://mikanani.me/Home/Episode/9aac876cbc4ba1d3a5ce82cac18d61cfdc5c4498</link>
>       <guid isPermaLink="true">https://mikanani.me/Home/Episode/9aac876cbc4ba1d3a5ce82cac18d61cfdc5c4498</guid>
>     </item>
>   </channel>
> </rss>
> ```

感谢，已经解决
