### ISSUE TITLE
Season为02时sonarr下载完成后会导出到Season01

### ISSUE THREAD

**Issue by kolicime** [std4453/mikanarr#8]
在rss获取资源的时候是第二季，但下载完成后会import到第一季，如果第一季已有内容会直接覆盖
目前我下载异世界食堂2和星期一的丰满2时都遇到了这个问题

**Comment by kolicime** [comment]
找到了类似的案例，这似乎是sonarr的问题，sonarr不能很好的识别动画的命名，更改设置里的`Anime Episode Format`不知是否会有效果
https://github.com/Sonarr/Sonarr/issues/1951
https://github.com/Sonarr/Sonarr/issues/3677

**Comment by joseph-cheung** [comment]
请问有什么解决的办法吗

**Comment by kolicime** [comment]
> 请问有什么解决的办法吗

还没有，sonarr的命名有一定的格式要求，没办法把Anime Episode Format改成各字幕组的命名格式。
如果后续sonarr支持强制根据获取到的集数来重命名，这个问题就能解决了，但看起来短期内似乎是没什么希望。
还有一个思路是利用下载器的api（[比如qb的](https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html#qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_rename_file)）来在sonarr接管视频之前，先把视频重命名成sonarr支持的格式

**Comment by mutsumi63** [comment]
sonarr好像有api 不知道可以通过api来么

**Comment by mutsumi63** [comment]
sonarr里面有个Connections 可以在Download Upgrade Rename等event时候去调其他的webhook 或许可以在这个时候去改名？

**Comment by kolicime** [comment]
> sonarr里面有个Connections 可以在Download Upgrade Rename等event时候去调其他的webhook 或许可以在这个时候去改名？

等大佬造轮子吧，现在感觉这一套系统用来追番实在是太臃肿了些，而且效果也不理想，已经该用其他方案了

**Comment by mutsumi63** [comment]
> > sonarr里面有个Connections 可以在Download Upgrade Rename等event时候去调其他的webhook 或许可以在这个时候去改名？
> 
> 等大佬造轮子吧，现在感觉这一套系统用来追番实在是太臃肿了些，而且效果也不理想，已经该用其他方案了

感觉直接把sonarr直接fork个 db的数据源直接改成中文数据源比较好 例如改成mikan和bgm这种的  用api改限制太多

**Comment by std4453** [comment]
Sonarr不太适应中文动画，检测经常有问题，比较严重的例子是1月的PCR第二季，Sonarr会直接识别为1~12集，根本没法导入，目前没有好的解决方案。

我之前考虑的方案是接管qbt，因为qbt的web api有文档，只要在下载完之后重命名，然后再告知sonarr就行了，理论上可以这么搞，但比较麻烦，最后没有付诸实践。

我的新项目已经写差不多了，总的来说完全替代了Sonarr+mikanarr，目前在4月新番测试，不过要开源还比较麻烦，因为部署配置也写在里面，最近也比较忙，可能5~6月会想办法开源出来。

**Comment by SanaeMio** [comment]
今天我测试出一种办法解决这个问题，不过可能需要一种简单的轮子。。
思路是：在Sonarr发给qb下载请求之后，重命名下载任务为mikanarr转换之后rss对应的title（可以通过hash检索条目），Sonarr会不断轮询获取qb的下载进度，而Sonarr的Release Title就是获取的qb里的任务名称，前面的重命名之后的任务名称会被更新到Sonarr里。当任务下载完成后，Sonarr会根据Release Title来解析季度和集数，此前的重命名可以被Sonarr解析成功，会正确导入处理到对应季度的文件夹下。
目前应该是需要一种服务，先在Sonarr新增一个connect连接，On Grab时发送给某种服务，它再通过qb的web api将下载任务改名即可。目前我在qb的webui里手动改任务名已经成功了。

**Comment by mutsumi63** [comment]
> Sonarr不太适应中文动画，检测经常有问题，比较严重的例子是1月的PCR第二季，Sonarr会直接识别为1~12集，根本没法导入，目前没有好的解决方案。
> 
> 我之前考虑的方案是接管qbt，因为qbt的web api有文档，只要在下载完之后重命名，然后再告知sonarr就行了，理论上可以这么搞，但比较麻烦，最后没有付诸实践。
> 
> 我的新项目已经写差不多了，总的来说完全替代了Sonarr+mikanarr，目前在4月新番测试，不过要开源还比较麻烦，因为部署配置也写在里面，最近也比较忙，可能5~6月会想办法开源出来。

期待下lz的新项目，最近还找到个新的index提供器叫Prowlarr 有索引和下载调用功能 看看会不会有能有用到的地方

**Comment by sagehou** [comment]
> 

我写了个脚本，也是用这个思路的，sonarr抓到之后调用qb的webapi修改文件名，试用了一周，效果蛮好，没有再导入Season 1，可以参考一下。
https://github.com/sagehou/mikanarr/blob/1b5655e390009957cb77cd448a45f72bb2b16caf/auto_qb_rename.sh

**Comment by sagehou** [comment]
> 今天我测试出一种办法解决这个问题，不过可能需要一种简单的轮子。。 思路是：在Sonarr发给qb下载请求之后，重命名下载任务为mikanarr转换之后rss对应的title（可以通过hash检索条目），Sonarr会不断轮询获取qb的下载进度，而Sonarr的Release Title就是获取的qb里的任务名称，前面的重命名之后的任务名称会被更新到Sonarr里。当任务下载完成后，Sonarr会根据Release Title来解析季度和集数，此前的重命名可以被Sonarr解析成功，会正确导入处理到对应季度的文件夹下。 目前应该是需要一种服务，先在Sonarr新增一个connect连接，On Grab时发送给某种服务，它再通过qb的web api将下载任务改名即可。目前我在qb的webui里手动改任务名已经成功了。

我写了个脚本，也是用这个思路的，sonarr抓到之后调用qb的webapi修改文件名，试用了一周，效果蛮好，没有再导入Season 1，可以参考一下。
https://github.com/sagehou/mikanarr/blob/1b5655e390009957cb77cd448a45f72bb2b16caf/auto_qb_rename.sh

**Comment by SanaeMio** [comment]
> > 今天我测试出一种办法解决这个问题，不过可能需要一种简单的轮子。。 思路是：在Sonarr发给qb下载请求之后，重命名下载任务为mikanarr转换之后rss对应的title（可以通过hash检索条目），Sonarr会不断轮询获取qb的下载进度，而Sonarr的Release Title就是获取的qb里的任务名称，前面的重命名之后的任务名称会被更新到Sonarr里。当任务下载完成后，Sonarr会根据Release Title来解析季度和集数，此前的重命名可以被Sonarr解析成功，会正确导入处理到对应季度的文件夹下。 目前应该是需要一种服务，先在Sonarr新增一个connect连接，On Grab时发送给某种服务，它再通过qb的web api将下载任务改名即可。目前我在qb的webui里手动改任务名已经成功了。
> 
> 我写了个脚本，也是用这个思路的，sonarr抓到之后调用qb的webapi修改文件名，试用了一周，效果蛮好，没有再导入Season 1，可以参考一下。 https://github.com/sagehou/mikanarr/blob/1b5655e390009957cb77cd448a45f72bb2b16caf/auto_qb_rename.sh

辛苦啦，其实4月的时候我找朋友已经做了一套工具出来了，名叫[Xarr-Rss](https://xiaoyi510.github.io/xarr-rss/)，把自己遇到的所有痛点都解决了，包括这个issue提到的这个场景，您也可以试试看
