### ISSUE TITLE
减小dockers镜像体积

### ISSUE THREAD

**Issue by Izumiko** [std4453/mikanarr#9]
测试了一下multi-stage构建，并且用pkg把脚本打包成了一个单独的程序，最终镜像大小是24MB，小了很多。

镜像：[izumiko/mikanarr](https://hub.docker.com/r/izumiko/mikanarr/tags)

[Dockerfile](https://github.com/Izumiko/mikanarr/blob/master/Dockerfile)

**Comment by Shuenhoy** [comment]
@Izumiko 你把这个改进cherry-pick到一个单独的分支然后提一个PR吧。我去看看能不能联系到作者让他合并掉。

**Comment by Izumiko** [comment]
@Shuenhoy PR已发 #18
